RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 5000
CHUNK_OVERLAP: 100
DATA_PATH: "data/"
MAX_NEW_TOKENS: 256
TEMPERATURE: 0.01
MODEL_NAME: "mistralai/Codestral-22B-v0.1"
MODEL_TYPE: "no_OpenAI"
RERANKING: "yes"
